[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Po-Han, Huang, Powered by <a class="text-muted" href="https://thulite.io/">Thulite</a> and <a class="text-muted" href="https://gohugo.io/">Hugo</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[zh]
  languageName = "繁體中文"
  contentDir = "content/zh"
  weight = 15
  [zh.params]
    languageISO = "zh"
    languageTag = "zh-TW"
    footer = 'Po-Han, Huang, Powered by <a class="text-muted" href="https://thulite.io/">Thulite</a> and <a class="text-muted" href="https://gohugo.io/">Hugo</a>'
    alertText = '新版本已推出！<a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'