[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by <a class="text-muted" href="https://thulite.io/">Thulite</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[zh]
  languageName = "繁體中文"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "zh"
    languageTag = "zh-TW"
    footer = 'Gebaut mit <a class="text-muted" href="https://thulite.io/">Thulite</a>'
    alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'