name: Keep Codespaces Alive
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # fixed to 5 fields

jobs:
  ping:
    runs-on: ubuntu-latest
    # expose the token so GH CLI picks it up
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: List Codespaces
        id: list
        run: |
          echo "::set-output name=names::$(gh codespace list --json name \
            | jq -r '.[].name' | paste -sd " " -)"

      - name: Ping each Codespace
        run: |
          for cs in ${{ steps.list.outputs.names }}; do
            echo "⏳ Pinging codespace $cs…"
            gh codespace exec -c "$cs" --echo "ping" || true
          done
